### ISSUE TITLE
cxxtools-3.0rc1 test suite fails on ppc64 and ppc64le

### ISSUE THREAD

**Issue by martinkg** [maekitalo/cxxtools#14]
test fails on Fedora ppc64 and ppc64le with this error:

serializationinfo::testRangeCheck: ASSERTION at serializationinfo-test.cpp:501
	exception of type std::range_error expected in siValue<double>(si)

ppc64 build.log:
https://kojipkgs.fedoraproject.org//work/tasks/5767/18075767/build.log

ppc64le build.log:
https://kojipkgs.fedoraproject.org//work/tasks/5765/18075765/build.log

**Comment by maekitalo** [comment]
I checked the log. The serialization info test is a wrong test. It relies too much on double characteristics and obviously fails therefore on ppc64. I will improve the test case.
There is another failed test with the rpc servers. I currently have no idea, how that can fail and how that can be processor specific since those tests work fine on other platforms. I do not have access to a ppc64 system and hence can't debug it. Do you have the chance to analyse it further?

**Comment by martinkg** [comment]
> I checked the log. The serialization info test is a wrong test. It relies too much on double characteristics > and obviously fails therefore on ppc64. I will improve the test case.
ok

> There is another failed test with the rpc servers. I currently have no idea, how that can fail and how that > can be processor specific since those tests work fine on other platforms. I do not have access to a
> ppc64 system and hence can't debug it. Do you have the chance to analyse it further?
Even I have no ppc64 system, but I can have compile the code on the Fedora build system.

**Comment by martinkg** [comment]
the test-suite of the recent git version cxxtools-92490b50724406a2ccf8587366079206f4e992f3
fails now with this error:
jsonrpc::Multiple: ASSERTION at jsonrpc-test.cpp:801
	not equal:
	value1 (procs[i].end(2000))=
		<0>
	value2 (i*i)=
		<100>

entire build.log:
https://kojipkgs.fedoraproject.org//work/tasks/8862/18178862/build.log

**Comment by martinkg** [comment]
will close this ticket, because there is a new version fo cxxtools available.
